version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "beta-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3y4t943q3zqk"
s3_prefix = "beta-1"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
